[package]
name = "cardano-submit-api"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
pallas-network = { git = "https://github.com/kettlebell/pallas.git", branch = "conway_update" }
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "20d8c963a17098d3448a2b88fbeae4e2b3a3f150" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "20d8c963a17098d3448a2b88fbeae4e2b3a3f150" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "20d8c963a17098d3448a2b88fbeae4e2b3a3f150" }
tokio = { version = "1", features = ["full"] }
hex = "0.4.3"
thiserror = "1.0.47"
log = "0.4.20"