[package]
name = "cardano-submit-api"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
pallas-network = { git = "https://github.com/GusevTimofey/pallas.git", rev = "c667bb3" }
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "92fa3944388c51880a77209feda35e16e0289247" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "92fa3944388c51880a77209feda35e16e0289247" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", rev = "92fa3944388c51880a77209feda35e16e0289247" }
tokio = { version = "1", features = ["full"] }
hex = "0.4.3"
thiserror = "1.0.47"
log = "0.4.20"