/// Effect that can be generated by the engine itself as a result of execution.
#[derive(Debug, Clone, Eq, PartialEq)]
pub enum InternalEffect<Fr, Pl, Src> {
    FragmentsAvailable(Vec<Fr>, Src),
    PoolUpdated(Pl, Src),
}
