[package]
name = "snek-cardano-agent"
version = "1.0.0"
edition = "2021"
rust-version = "1.80.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-primitives = { version = "0.1.0", path = "../concurrent-primitives" }
spectrum-streaming = { version = "0.1.0", path = "../spectrum-streaming" }
bloom-offchain = { version = "1.0.0", path = "../bloom-offchain" }
bloom-offchain-cardano = { version = "1.0.0", path = "../bloom-offchain-cardano" }
spectrum-offchain = { version = "0.1.0", path = "../spectrum-offchain", features = ["cml-chain"] }
spectrum-offchain-cardano = { version = "1.0.0", path = "../spectrum-offchain-cardano" }
cardano-chain-sync = { version = "0.1.0", path = "../cardano-chain-sync" }
cardano-explorer = { version = "0.1.0", path = "../cardano-explorer" }
cml-core = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "fix-datum-hash" }
cardano-mempool-sync = { version = "0.1.0", path = "../cardano-mempool-sync" }
spectrum-cardano-lib = { version = "0.1.0", path = "../spectrum-cardano-lib" }
cml-crypto = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "fix-datum-hash" }
cml-chain = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "fix-datum-hash" }
cml-multi-era = { git = "https://github.com/oskin1/cardano-multiplatform-lib.git", branch = "fix-datum-hash" }
futures = "0.3.25"
tokio = { version = "1.42.0", features = ["full"] }
log = "0.4.17"
log4rs = "1.2.0"
rand = { version = "0.8.5", features = ["small_rng"] }
type-equalities = "0.3.1"
serde = { version = "1.0.147", features = ["derive"] }
bounded-integer = { version = "0.5.7", features = ["types", "serde1"] }
serde_json = "1.0.88"
tracing = "0.1.31"
tracing-subscriber = "0.3.17"
clap = { version = "4.0", features = ["derive"] }
either = "1.9.0"

[dev-dependencies]
spectrum-offchain-cardano = { version = "1.0.0", path = "../spectrum-offchain-cardano" }
